### ISSUE TITLE
Geb does not start chrome driver

### ISSUE THREAD

**Issue by ntung** [grails-samples/geb-example-grails#1]
Hi Sergio,

I tried this example in Grails 3 workshop in Madrid two days ago and it works fine. I can see it opens Chrome and Firefox to run tests automatically. But it seems to go wrong when I am trying it now without showing any browser windows. The following is shown when the integration tests conclude.
`:integrationTest
 -- Test test get(demo.ExtraDataServiceSpec)
Grails application running at http://localhost:43201 in environment: test
demo.ExtraDataServiceSpec > test get PASSED
 -- Test test list(demo.ExtraDataServiceSpec)
demo.ExtraDataServiceSpec > test list PASSED
 -- Test test count(demo.ExtraDataServiceSpec)
demo.ExtraDataServiceSpec > test count PASSED
 -- Test test delete(demo.ExtraDataServiceSpec)
demo.ExtraDataServiceSpec > test delete PASSED
 -- Test test save(demo.ExtraDataServiceSpec)
demo.ExtraDataServiceSpec > test save PASSED
 -- Test test get(demo.RoomDataServiceSpec)
demo.RoomDataServiceSpec > test get PASSED
 -- Test test list(demo.RoomDataServiceSpec)
demo.RoomDataServiceSpec > test list PASSED
 -- Test test count(demo.RoomDataServiceSpec)
demo.RoomDataServiceSpec > test count PASSED
 -- Test test delete(demo.RoomDataServiceSpec)
demo.RoomDataServiceSpec > test delete PASSED
 -- Test test save(demo.RoomDataServiceSpec)
demo.RoomDataServiceSpec > test save PASSED
 -- Test test get(demo.BookingDataServiceSpec)
demo.BookingDataServiceSpec > test get PASSED
 -- Test test list(demo.BookingDataServiceSpec)
demo.BookingDataServiceSpec > test list PASSED
 -- Test test count(demo.BookingDataServiceSpec)
demo.BookingDataServiceSpec > test count PASSED
 -- Test test delete(demo.BookingDataServiceSpec)
demo.BookingDataServiceSpec > test delete PASSED
 -- Test test save(demo.BookingDataServiceSpec)
demo.BookingDataServiceSpec > test save PASSED

:mergeTestReports

BUILD SUCCESSFUL

Total time: 22.295 secs

10:43:06: Task execution finished 'integrationTest'.
`

Could you clarify the code pls?

**Comment by sdelamo** [comment]
The Geb tests are annotated with:

`@IgnoreIf({ !System.getProperty('geb.env') })`

See: https://github.com/grails-samples/geb-example-grails/blob/master/src/integration-test/groovy/demo/BookingCRUDSpec.groovy#L18

They are ignored unless you pass the System property `geb.env`. To run every integration Tests ( including Geb ones) do:

e.g. .`./gradlew -Dgeb.env=chrome iT`

Please, open the issue if you are still facing problems.
